const speakers = [
  {
    title: 'Proactive scalable local area network',
    name: 'Dexter Nairns',
    jobTitle: 'Payment Adjustment Coordinator',
    time: '2020-05-31T11:00',
    photo:
      'https://robohash.org/inciduntaliquidtempore.bmp?size=200x200&set=set1',
  },
  {
    title: 'Implemented cohesive instruction set',
    name: 'Zaria Eglinton',
    jobTitle: 'Database Administrator II',
    time: '2020-05-31T11:00',
    photo:
      'https://robohash.org/praesentiumcommodialiquam.png?size=200x200&set=set1',
  },
  {
    title: 'Public-key clear-thinking access',
    name: 'Karlen Insall',
    jobTitle: 'Technical Writer',
    time: '2020-05-31T11:00',
    photo:
      'https://robohash.org/voluptatesaliasomnis.png?size=200x200&set=set1',
  },
  {
    title: 'Upgradable non-volatile function',
    name: 'Robbi Lacroux',
    jobTitle: 'Automation Specialist II',
    time: '2020-05-31T11:00',
    photo:
      'https://robohash.org/necessitatibusveniamaut.jpg?size=200x200&set=set1',
  },
  {
    title: 'Profit-focused dynamic archive',
    name: 'Nariko Elan',
    jobTitle: 'Associate Professor',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/estdolorumautem.jpg?size=200x200&set=set1',
  },
  {
    title: 'Proactive static complexity',
    name: 'Gaylor Geistbeck',
    jobTitle: 'VP Marketing',
    time: '2020-05-31T11:00',
    photo:
      'https://robohash.org/doloremqueinciduntquis.jpg?size=200x200&set=set1',
  },
  {
    title: 'Distributed impactful instruction set',
    name: 'Maryanna Bampforth',
    jobTitle: 'Senior Quality Engineer',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/quidemeumdicta.bmp?size=200x200&set=set1',
  },
  {
    title: 'Function-based incremental capacity',
    name: 'Ariela Dymidowski',
    jobTitle: 'Accounting Assistant II',
    time: '2020-05-31T11:00',
    photo: 'https://robohash.org/sitmagniaut.png?size=200x200&set=set1',
  },
  {
    title: 'Implemented background neural-net',
    name: 'Sheridan Wrankmore',
    jobTitle: 'Legal Assistant',
    time: '2020-05-31T17:00',
    photo:
      'https://robohash.org/laborumautemdistinctio.jpg?size=200x200&set=set1',
  },
  {
    title: 'Mandatory 24 hour interface',
    name: 'Dorise Walsh',
    jobTitle: 'Quality Engineer',
    time: '2020-06-01T21:00',
    photo: 'https://robohash.org/etrepudiandaeautem.png?size=200x200&set=set1',
  },
  {
    title: 'Secured 5th generation open system',
    name: 'Heindrick Whitby',
    jobTitle: 'VP Quality Control',
    time: '2020-06-02T11:00',
    photo: 'https://robohash.org/abestvoluptatem.jpg?size=200x200&set=set1',
  },
  {
    title: 'Multi-layered global artificial intelligence',
    name: 'Francklyn Perview',
    jobTitle: 'Programmer III',
    time: '2020-06-02T16:00',
    photo: 'https://robohash.org/voluptascumquequia.jpg?size=200x200&set=set1',
  },
  {
    title: 'Upgradable eco-centric interface',
    name: 'Bernadina Guyton',
    jobTitle: 'Associate Professor',
    time: '2020-05-31T11:00',
    photo: 'https://robohash.org/quonullafacilis.bmp?size=200x200&set=set1',
  },
  {
    title: 'Integrated user-facing circuit',
    name: 'Lorelle Piechnik',
    jobTitle: 'General Manager',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/ullamutsoluta.png?size=200x200&set=set1',
  },
  {
    title: 'Universal high-level structure',
    name: 'Trevar Hames',
    jobTitle: 'Dental Hygienist',
    time: '2020-05-31T11:00',
    photo: 'https://robohash.org/fugitseddolores.jpg?size=200x200&set=set1',
  },
  {
    title: 'Exclusive 24 hour instruction set',
    name: 'Avis Darnody',
    jobTitle: 'Project Manager',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/recusandaeinenim.bmp?size=200x200&set=set1',
  },
  {
    title: 'Down-sized value-added interface',
    name: 'Aleece Ayars',
    jobTitle: 'Software Test Engineer IV',
    time: '2020-06-01T11:00',
    photo:
      'https://robohash.org/sintdistinctiovoluptas.jpg?size=200x200&set=set1',
  },
  {
    title: 'Versatile high-level process improvement',
    name: 'Joannes Haggath',
    jobTitle: 'Compensation Analyst',
    time: '2020-05-31T11:00',
    photo: 'https://robohash.org/estvoluptasitaque.jpg?size=200x200&set=set1',
  },
  {
    title: 'Multi-layered eco-centric Graphical User Interface',
    name: 'Rikki Featenby',
    jobTitle: 'Geologist IV',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/doloremagniquia.png?size=200x200&set=set1',
  },
  {
    title: 'Extended tertiary complexity',
    name: 'Waldo Nice',
    jobTitle: 'Research Nurse',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/nequeearumfuga.bmp?size=200x200&set=set1',
  },
  {
    title: 'Innovative even-keeled flexibility',
    name: 'Deb Mityashev',
    jobTitle: 'Administrative Officer',
    time: '2020-05-31T11:00',
    photo: 'https://robohash.org/quiasuntest.png?size=200x200&set=set1',
  },
  {
    title: 'Multi-layered optimal pricing structure',
    name: 'Dacy Gonoude',
    jobTitle: 'Food Chemist',
    time: '2020-06-02T09:00',
    photo:
      'https://robohash.org/omnisrepudiandaedoloremque.png?size=200x200&set=set1',
  },
  {
    title: 'Vision-oriented local function',
    name: 'Haydon Mathew',
    jobTitle: 'Pharmacist',
    time: '2020-05-31T11:00',
    photo:
      'https://robohash.org/occaecatilaboriosamaliquid.png?size=200x200&set=set1',
  },
  {
    title: 'Monitored solution-oriented workforce',
    name: 'Lorie Quene',
    jobTitle: 'Project Manager',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/etrepudiandaeomnis.bmp?size=200x200&set=set1',
  },
  {
    title: 'Integrated eco-centric methodology',
    name: 'Hewie Fochs',
    jobTitle: 'Automation Specialist II',
    time: '2020-05-31T11:00',
    photo: 'https://robohash.org/velitdoloraut.jpg?size=200x200&set=set1',
  },
  {
    title: 'Compatible fresh-thinking forecast',
    name: 'Abey Strover',
    jobTitle: 'Data Coordiator',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/quiducimusdolores.png?size=200x200&set=set1',
  },
  {
    title: 'Team-oriented stable help-desk',
    name: 'Howie Nials',
    jobTitle: 'Quality Control Specialist',
    time: '2020-06-01T11:00',
    photo:
      'https://robohash.org/quiaaccusamusdebitis.png?size=200x200&set=set1',
  },
  {
    title: 'User-friendly 4th generation circuit',
    name: 'Lenka Bussens',
    jobTitle: 'VP Product Management',
    time: '2020-06-01T11:00',
    photo: 'https://robohash.org/velitaqueomnis.jpg?size=200x200&set=set1',
  },
  {
    title: 'Programmable 4th generation implementation',
    name: 'Jessalin Gingles',
    jobTitle: 'Cost Accountant',
    time: '2020-05-31T11:00',
    photo: 'https://robohash.org/omnisminimaeum.png?size=200x200&set=set1',
  },
  {
    title: 'Visionary client-server installation',
    name: 'Yolanthe Wigmore',
    jobTitle: 'Senior Developer',
    time: '2020-05-31T11:00',
    photo: 'https://robohash.org/quiaquasiet.png?size=200x200&set=set1',
  },
];
export default speakers;
